my_string = input("Привет! Как тебя зовут: ")
print(len(my_string))
my_string = ("Привет! Как тебя зовут: ")
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ",""))
print(my_string[0])
print(my_string[-3])
